# Generated by Django 5.0.4 on 2024-04-19 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='company/')),
                ('address', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=255)),
                ('kpp', models.CharField(max_length=255)),
                ('okpo', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('account_number1', models.FloatField()),
                ('account_number2', models.FloatField()),
                ('account_number3', models.FloatField()),
                ('kor_shot', models.CharField(max_length=255)),
                ('bike', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='contract_title', max_length=255)),
                ('akt', models.FileField(upload_to='contract/')),
                ('invoice', models.FileField(upload_to='contract/')),
                ('zayavka', models.FileField(upload_to='contract/')),
                ('cmr', models.FileField(upload_to='contract/')),
                ('contract_number', models.CharField(max_length=255)),
                ('cost', models.FloatField()),
                ('auto_number', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='logistics.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
